# Generated by Django 4.0.2 on 2022-02-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=None, null=True)),
                ('student_size', models.IntegerField(default=None, null=True)),
                ('admissions_rate', models.FloatField(default=None, null=True)),
                ('program_percent_agriculture', models.FloatField(default=None, null=True)),
                ('program_percent_resources', models.FloatField(default=None, null=True)),
                ('program_percent_architecture', models.FloatField(default=None, null=True)),
                ('program_percent_ethnic_cultural_gender', models.FloatField(default=None, null=True)),
                ('program_percent_communication', models.FloatField(default=None, null=True)),
                ('program_percent_communications_technology', models.FloatField(default=None, null=True)),
                ('program_percent_computer', models.FloatField(default=None, null=True)),
                ('program_percent_personal_culinary', models.FloatField(default=None, null=True)),
                ('program_percent_education', models.FloatField(default=None, null=True)),
                ('program_percent_engineering', models.FloatField(default=None, null=True)),
                ('program_percent_engineering_technology', models.FloatField(default=None, null=True)),
                ('program_percent_language', models.FloatField(default=None, null=True)),
                ('program_percent_family_consumer_science', models.FloatField(default=None, null=True)),
                ('program_percent_legal', models.FloatField(default=None, null=True)),
                ('program_percent_english', models.FloatField(default=None, null=True)),
                ('program_percent_humanities', models.FloatField(default=None, null=True)),
                ('program_percent_library', models.FloatField(default=None, null=True)),
                ('program_percent_biological', models.FloatField(default=None, null=True)),
                ('program_percent_mathematics', models.FloatField(default=None, null=True)),
                ('program_percent_military', models.FloatField(default=None, null=True)),
                ('program_percent_multidiscipline', models.FloatField(default=None, null=True)),
                ('program_percent_parks_recreation_fitness', models.FloatField(default=None, null=True)),
                ('program_percent_philosophy_religious', models.FloatField(default=None, null=True)),
                ('program_percent_theology_religious_vocation', models.FloatField(default=None, null=True)),
                ('program_percent_physical_science', models.FloatField(default=None, null=True)),
                ('program_percent_science_technology', models.FloatField(default=None, null=True)),
                ('program_percent_psychology', models.FloatField(default=None, null=True)),
                ('program_percent_security_law_enforcement', models.FloatField(default=None, null=True)),
                ('program_percent_public_administration_social_service', models.FloatField(default=None, null=True)),
                ('program_percent_social_science', models.FloatField(default=None, null=True)),
                ('program_percent_construction', models.FloatField(default=None, null=True)),
                ('program_percent_mechanic_repair_technology', models.FloatField(default=None, null=True)),
                ('program_percent_precision_production', models.FloatField(default=None, null=True)),
                ('program_percent_transportation', models.FloatField(default=None, null=True)),
                ('program_percent_visual_performing', models.FloatField(default=None, null=True)),
                ('program_percent_health', models.FloatField(default=None, null=True)),
                ('program_percent_business_marketing', models.FloatField(default=None, null=True)),
                ('program_percent_history', models.FloatField(default=None, null=True)),
                ('student_ethnicity_black', models.FloatField(default=None, null=True)),
                ('student_ethnicity_hispanic', models.FloatField(default=None, null=True)),
                ('student_ethnicity_asian', models.FloatField(default=None, null=True)),
                ('student_ethnicity_white', models.FloatField(default=None, null=True)),
                ('student_ethnicity_aian', models.FloatField(default=None, null=True)),
                ('student_ethnicity_nhpi', models.FloatField(default=None, null=True)),
                ('student_ethnicity_two_or_more', models.FloatField(default=None, null=True)),
                ('student_ethnicity_non_resident_alien', models.FloatField(default=None, null=True)),
                ('student_ethnicity_unknown', models.FloatField(default=None, null=True)),
                ('student_ethnicity_white_non_hispanic', models.FloatField(default=None, null=True)),
                ('student_ethnicity_black_non_hispanic', models.FloatField(default=None, null=True)),
                ('student_ethnicity_asian_pacific_islander', models.FloatField(default=None, null=True)),
                ('school', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_relation', to='school.school')),
            ],
            options={
                'verbose_name': 'school year',
                'verbose_name_plural': 'school years',
                'db_table': 'schools_school_year',
                'ordering': ['year'],
                'abstract': False,
                'unique_together': {('school_id', 'year')},
            },
        ),
    ]
