# Generated by Django 4.1.2 on 2022-11-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.organization')),
                ('main_campus', models.BooleanField(default=None, null=True)),
                ('ownership', models.CharField(default=None, max_length=256, null=True)),
                ('url', models.URLField(default=None, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'db_table': 'schools_school',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('organization.organization',),
        ),
    ]
